apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: mongodb-env-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: mongodb-secrets
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: mongodb-secrets
        property: MONGO_INITDB_ROOT_PASSWORD
    - secretKey: MONGO_INITDB_DATABASE
      remoteRef:
        key: mongodb-secrets
        property: MONGO_INITDB_DATABASE
